### ISSUE TITLE
gdb_bootloader: Original app code fails with the BSL

### ISSUE THREAD

**Issue by lunakid** [RickKimball/msp430_code#2]
Hi Rick! Just started playing with your cool gdb_bootloader.
After trying with a simple LED blinker, which was OK, I went ahead and added it to a more serious one using stuff like the HW UART, SPI with USCI/B, running at 1MHz (calib) with ACLK @ VLO (to wake from LPM3).

(The chip (553) is off the Launchpad (on a breadboard), but still connected for SBWing and for the LEDs.)

After uploading the BSL and then my original FW (plain ~3K ELF), either simply by mspdebug "load" (should also work, right?) or gdb "load" (via your BSL), I see my app running severely crippled: 
- sometimes the clocks seems to be off, but (UART TX still works, so not sure). 
- UART RX seems to not work at all (interrupt flags mismatch?)
- and sometimes the MCU even resets itself randomly, or consistently (apparently when waking up from LP3), or upon the UART RX interrupt

I have not started fully debugging it all out, first I wanted to ask you: 

Can you remember what setup the MSP is initialized with by Fabooh that may interfere with my code (considering the symptoms above)?

(NOTE: My app does some init that depends on a clean PUC state. Also, I loaded my FW via GDB *without* an erase first (despite your instructions); just doing "load". Can that be a problem?
I have an USCIAB0RX_VECTOR and an TIMER0_A0_VECTOR ISR, if that matters.)

Thanks a lot!

**Comment by RickKimball** [comment]
You might want to try this version:

https://github.com/RickKimball/fabooh/tree/master/board/msp430g2553in20/apps/gdb_bootloader

**Comment by lunakid** [comment]
Thanks for the quick turnaround. Still having issues (seems to be the same thing, actually, but haven't thoroughly tested, I'll need to go deeper into it tomorrow).

**Comment by RickKimball** [comment]
The bootloader does setup the clocks for 16MHz.  You might try running your code faster or modifying the bootloader to run at 1 MHz too.  The bootloader doesn't touch the ACLK. It doesn't use interrupt handlers.  It does setup the button an input using the internal pullup.

It might be interesting to see your code.

**Comment by RickKimball** [comment]
I just gave the ascii_table example a try.  It seemed to work fine.  I then changed the MCLK_FREQ=1000000UL and that also worked fine.  It might help to post a link to your code.

**Comment by lunakid** [comment]
Thanks! I do reset the clock back to 1MHz (calib.) in my app, though. (And disable LFXT1 and use VLO for ACLK). 
My stuff is not online yet, and (rather: "because") it's such a mess in its current transient state that it's probably more productive to understand your stuff than get you make sense of mine. ;) 
But I'll try to narrow it down to a simplified example and then post it as a test case.

**Comment by lunakid** [comment]
("I just gave the ascii_table example a try. It seemed to work fine." -- If that's from Fabooh, then note that all the Fabooh examples would probably work fine, as they go through the same setup sequence as the bootloader, which is also a Fabooh app.)

**Comment by RickKimball** [comment]
I had tested this latest version with code using CCS.  That was actually the last change real change to the code.  With CCS, the address of the reset vector jumps around randomly. msp430-gcc the reset vector handler would always end up at 0xc000.   I'll try to find some uart sample code for CCS and try it.

**Comment by RickKimball** [comment]
OK using the online dev compiler at dev.ti.com, I tried the example called msp430g2xx3_uscia0_uart_01_9600.  It uses the uart port at 9600 baud and echos back each character typed using an interrupt handler.  Seems to work fine.

**Comment by RickKimball** [comment]
BTW, all these tests are using the newest version of this code at:
https://github.com/RickKimball/fabooh/tree/master/board/msp430g2553in20/apps/gdb_bootloader

**Comment by lunakid** [comment]
Cool, thanks!

In the meantime, just to make sure I understand things right...
What exactly dos "erasing" the flash mean before uploading firmware?
a) Does it do the low-level bit-wise "flash baselining" simply to allow writing properly at all?
b) Or does "erase" means erasing the *whole* memory -- being optional in the sense that an upload (without an erase first) will still correctly write all the bytes that belong to the mem. space of a given app, just would not touch any other bytes?

IOW: Is erasing *mandatory* for any sensible fw upload at all, or, the contrary, is it actually *optional* for most of the fw cases?

**Comment by RickKimball** [comment]
I think msp430-gdb does the right thing, as in erasing segments before it writes.  So eraseflash is probably optional.
I've always used eraseflash. Call me paranoid.  It will erase each segment in memory, avoiding the segments that contain the bootloader code.  It does erase the vector table, so you don't end up with any errant vector address that may or may not contain valid code.  You can see the actual boot loader code here:

https://github.com/RickKimball/fabooh/blob/master/board/msp430g2553in20/apps/gdb_bootloader/gdb_bootloader.cpp#L299

**Comment by lunakid** [comment]
OK, thanks. (Yeah, I suspected your erase will do just something like that, but nice to see how it actually works! I'm learning all this remote GDB business right now, too, largely thanks to your stuff! :) )
Just started narrowing down the code... I noticed that the minimal UART I use is actually quite fragile *without* your bootloader, too! :) Just commenting out apparently irrelevant parts also seems to be able to kill it... :)
I'm almost sure the root cause is on my side, but still would be interesting to spot what interference triggers it.

**Comment by lunakid** [comment]
Nooo!!!!
It *is* the missing erase with GDB! :-ooo  :-/ 
OK, so, you are *NOT* paranoid with doing/suggesting it!... :) 
(I need to double-check it, so that your BSL is still really on the device, but that's not so easy, as I have no pushbutton at P1.3 in my setup (it is an SPI/SS), but I'll find a way...)

**Comment by lunakid** [comment]
BTW, I'll need to programmatically trigger bootstrap mode from the fw. 
Could you recommend a simple way other than writing some flag to flash? 
Like... how easy would it be to let the bootloader be hooked to NMI instead of RST?

**Comment by lunakid** [comment]
Without reopening this (I hope you'll still see it): I noticed one more thing.

Power consumption almost doubles when the bootloader is sitting there in the flash and the app is run through that. (Note: the code resets the clocks back to 1MHz.) I'll investigate this further. 

(I'd guess a GPIO direction conflict due to the LED and the switch the bootloader initializes not being in sync with the assumed PUC state.)
