### ISSUE TITLE
Trigger the BSL programmatically

### ISSUE THREAD

**Issue by lunakid** [RickKimball/msp430_code#3]
I'll need to programmatically trigger bootstrap mode from the fw.
Could you recommend a simple way other than writing some flag to flash?
Like... how easy would it be to get the bootloader be hooked optinoally to NMI instead of RST?
Or, just jumping over to an exported entry address (somewhere after checking the GPIO)? (You already have a "TODO: expose common routines..." in the BSL code. ;) ) Thanks again!

**Comment by RickKimball** [comment]
Please resubmit this question in the fabooh project

**Comment by lunakid** [comment]
Ahh, sorry, sure. (I was already in Fabooh in my mind all along...)
